apiVersion: v1
kind: ReplicationController
metadata:
  name: zookeeperrc
  labels:
    app: zookeeper
    name: zookeeper

spec:
  replicas: 1
  selector:
    name: zookeeper
    app: zookeeper
  template:
    metadata:
      labels:
        name: zookeeper
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: docker pull jplock/zookeeper
        # command:
        #   - /run.sh
        resources:
          limits:
            cpu: 0.1
        ports:
          - containerPort: 2181
            name: client
          - containerPort: 2888
            name: peer
          - containerPort: 3888
            name: leaderelection
