apiVersion: v1
kind: Service
metadata:
  name: zookeeperservice
  labels:
    tool: zookeeper

spec:
  ports:
  - name: client
    port: 2181
    protocol: TCP

  - name: peer
    port: 2888
    protocol: TCP

  - name: leaderelection
    port: 3888
    protocol: TCP

  selector:
    app: zookeeper
    name: zookeeper
